import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { DanbaekVoiceBubble } from '@/components/character/danbaek-voice-bubble';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { ChipRow } from '@/components/ui/chip-row';
import { NavRow } from '@/components/ui/nav-row';
import { PrimaryButton } from '@/components/ui/primary-button';
import { ScreenScroll } from '@/components/ui/screen-scroll';
import { Section } from '@/components/ui/section';
import { AiQuickActionLabels } from '@/config/ai-quick-actions';
import { StanleyPortraitImage } from '@/config/character-assets';
import { StanleyTrainer } from '@/config/trainers';
import { Layout, Radius, Spacing } from '@/constants/theme';
import { useAppData } from '@/context/app-data-context';
import { getTodayRecords } from '@/data/workout-repository';
import { useTheme } from '@/hooks/use-theme';
import { AiQuickActionId } from '@/services/trainer/ai-trainer-service';
import { buildDanbaekVoice } from '@/utils/danbaek-learning-presence';
import { buildTrainerBriefSections } from '@/utils/trainer-brief';
import { getGreetingLine } from '@/utils/trainer-dialogue';
const HERO_QUICK_ACTIONS:AiQuickActionId[]=['what_today','build_routine','ask_form','check_diet'];
export default function TrainerScreen(){const router=useRouter();const theme=useTheme();const{workoutRecords,streak,ptContext,danbaekLearning}=useAppData();const hasRecordedToday=getTodayRecords(workoutRecords).length>0;const[stanleyLine]=useState(()=>getGreetingLine(StanleyTrainer.dialogueSet,{hasRecordedToday,currentStreakDays:streak.currentStreakDays}).text);const brief=useMemo(()=>buildTrainerBriefSections(ptContext),[ptContext]);const danbaekVoice=useMemo(()=>buildDanbaekVoice(danbaekLearning),[danbaekLearning]);const openChat=(action?:AiQuickActionId)=>router.push(action?`/ai-chat?action=${action}`:'/ai-chat');return <ScreenScroll><View style={styles.hero}><ThemedView type="backgroundSelected" style={[styles.portraitSlot,{borderColor:theme.border}]}>{StanleyPortraitImage?<Image source={StanleyPortraitImage} style={styles.portraitImage} contentFit="cover"/>:<ThemedText style={styles.portraitEmoji}>{StanleyTrainer.portraitPlaceholder}</ThemedText>}</ThemedView><View style={styles.heroText}><ThemedText type="heading" numberOfLines={1}>{StanleyTrainer.displayName}</ThemedText><ThemedText type="caption" themeColor="textSecondary">내 담당 PT</ThemedText><ThemedText type="small" themeColor="textSecondary" style={styles.heroLine}>{stanleyLine}</ThemedText></View></View><Section title="오늘 상태"><ThemedView type="backgroundElement" style={[styles.briefCard,{borderColor:theme.border}]}><ThemedText type="smallBold">{brief.status}</ThemedText><ThemedText type="small" style={{color:theme.gold}}>{brief.focus}</ThemedText>{brief.records.map(line=><ThemedText key={line} type="caption" themeColor="textSecondary">{line}</ThemedText>)}</ThemedView></Section><DanbaekVoiceBubble line={danbaekVoice.line} status={danbaekVoice.status} onPress={()=>router.push('/(tabs)/workout')}/><PrimaryButton label="AI 상담" subLabel="오늘 뭘 할지 물어보세요" variant="gold" size="large" onPress={()=>openChat()}/><ChipRow bleed>{HERO_QUICK_ACTIONS.map(action=><Pressable key={action} onPress={()=>openChat(action)} style={[styles.quickAction,{backgroundColor:theme.backgroundElement,borderColor:theme.border}]}><ThemedText type="caption">{AiQuickActionLabels[action]}</ThemedText></Pressable>)}</ChipRow><Section title="내 기록 보기"><NavRow label="루틴 관리" value="내 루틴 보기" onPress={()=>router.push('/(tabs)/workout')}/><NavRow label="몸 변화" value="체중 · 사진 비교" onPress={()=>router.push('/(tabs)/history')}/><NavRow label="성장 리포트" value="HELL PASS 진행도" onPress={()=>router.push('/pass')}/></Section></ScreenScroll>;}
const styles=StyleSheet.create({hero:{flexDirection:'row',alignItems:'flex-start',gap:Spacing.three},portraitSlot:{width:96,height:128,borderRadius:Radius.large,borderWidth:1,alignItems:'center',justifyContent:'center',overflow:'hidden'},portraitImage:{width:'100%',height:'100%'},portraitEmoji:{fontSize:36,opacity:.45},heroText:{flex:1,gap:Spacing.half},heroLine:{marginTop:Spacing.one},briefCard:{borderWidth:1,borderRadius:Radius.medium,padding:Spacing.three,gap:Spacing.one},quickAction:{borderWidth:1,borderRadius:Radius.pill,paddingHorizontal:Spacing.three,paddingVertical:Spacing.two,minHeight:Layout.compactRowHeight-8,justifyContent:'center'}});
