import { MuscleGroupLabels } from '@/config/muscle-groups';
import type { MuscleGroup } from '@/types/exercise';
import { withObjectParticle, withSubjectParticle, withTopicParticle } from '@/utils/korean';
import type { PtContext, PtContextExercise } from '@/utils/pt-context';

function describeSet(exercise: PtContextExercise): string { if (!exercise.topSet) return `${exercise.name} ${exercise.setCount}세트`; return `${exercise.name} ${exercise.topSet.weightKg}kg × ${exercise.topSet.reps}회`; }
export function daysBetween(fromDate:string,toDate:string):number{const [fy,fm,fd]=fromDate.split('-').map(Number);const [ty,tm,td]=toDate.split('-').map(Number);return Math.round((new Date(ty,tm-1,td).getTime()-new Date(fy,fm-1,fd).getTime())/86_400_000);}
export function buildStatusLine(context:PtContext):string{const{today,recentTraining}=context;if(today.activeSession){const where=today.activeSession.currentExerciseName;return where?`지금 ${where} 하는 중이시죠. ${today.activeSession.completedSets}세트 끝났습니다.`:'운동 진행 중입니다. 계속하시죠.';}if(today.workoutCompleted)return'오늘 운동은 끝내셨네요. 수고하셨습니다.';if(!recentTraining.lastWorkoutDate)return'아직 기록이 없네요. 오늘 하나 찍으시죠.';const gap=daysBetween(recentTraining.lastWorkoutDate,today.date);if(gap<=1)return'어제 하셨네요. 오늘도 가시죠.';if(gap<=3)return`마지막 운동이 ${gap}일 전입니다. 오늘 오시죠.`;return`${gap}일 쉬셨습니다. 오늘은 가볍게라도 시작하시죠.`;}
export function buildWeeklyLine(context:PtContext):string{const{weeklyWorkoutCount,weeklyVolumeKg,streakDays}=context.recentTraining;const parts:string[]=[];parts.push(weeklyWorkoutCount>0?`이번 주 ${weeklyWorkoutCount}회`:'이번 주 기록 없음');if(weeklyVolumeKg>0)parts.push(`볼륨 ${weeklyVolumeKg.toLocaleString('ko-KR')}kg`);if(streakDays>0)parts.push(`연속 ${streakDays}일`);return parts.join(' · ');}
export function buildRecentTrainingLine(context:PtContext):string{const recent=context.recentTraining.recentExercises;if(recent.length===0)return'최근 세트 기록이 없어서 볼 게 없습니다.';return`최근에 ${recent.slice(0,2).map(describeSet).join(', ')} 하셨습니다.`;}
export function buildPrLine(context:PtContext):string|null{const[pr]=context.recentTraining.recentPRs;if(!pr)return null;if(pr.kind==='reps'){const load=pr.weightKg>0?`${pr.weightKg}kg`:'맨몸';return`${pr.name} ${load}로 ${pr.reps}회, 횟수 기록 넘기셨습니다.`;}return pr.previousBestWeightKg===null?`${withTopicParticle(pr.name)} ${pr.weightKg}kg가 첫 기록입니다.`:`${pr.name} ${pr.weightKg}kg, 이전 최고 ${pr.previousBestWeightKg}kg 넘기셨습니다.`;}
export function buildTodayPlanLine(context:PtContext,recommendedGroup:MuscleGroup|null,groupExerciseNames:string[]):string{if(context.today.activeSession)return buildStatusLine(context);if(context.currentRoutine&&context.currentRoutine.exercises.length>0)return`오늘은 ${context.currentRoutine.name} 예약돼 있습니다. 그대로 가시죠.`;if(!recommendedGroup)return'고른 루틴이 없으니 오늘 하고 싶은 부위로 시작하시죠.';const label=MuscleGroupLabels[recommendedGroup];if(groupExerciseNames.length===0)return`오늘은 ${label} 어떠십니까?`;return`한동안 ${withObjectParticle(label)} 안 하셨네요. ${groupExerciseNames.slice(0,2).join(', ')}부터 가시죠.`;}
export function buildExerciseRecordLine(exerciseName:string,recent:PtContextExercise|null):string{if(!recent)return`아직 ${exerciseName} 기록이 없네요.`;if(!recent.topSet)return`${withTopicParticle(exerciseName)} ${recent.date}에 ${recent.setCount}세트 하셨습니다.`;return`최근 ${withSubjectParticle(exerciseName)} ${recent.topSet.weightKg}kg ${recent.topSet.reps}회입니다 (${recent.date}).`;}
export interface TrainerBriefSections{status:string;focus:string;records:string[];}
export function buildTrainerBriefSections(context:PtContext):TrainerBriefSections{const status=buildStatusLine(context);const prLine=buildPrLine(context);const recentLine=buildRecentTrainingLine(context);const weeklyLine=buildWeeklyLine(context);const focus=prLine??recentLine;const records=[weeklyLine,focus===recentLine?null:recentLine].filter((line):line is string=>Boolean(line));return{status,focus,records};}
export function buildTrainerBrief(context:PtContext):string[]{return[buildStatusLine(context),buildWeeklyLine(context),buildRecentTrainingLine(context),buildPrLine(context)].filter((line):line is string=>Boolean(line));}
